const MEALS=["Breakfast","Lunch","Break-fast 4pm","Supper"], PIN="1960";
let db, staffMeal="", studentMeal="", scanTarget="", stream=null, scanning=false, timer=null, refreshTimer=null, pinPurpose="staff";
const $=id=>document.getElementById(id), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Africa/Harare',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
function init(){db=supabase.createClient(APP_CONFIG.SUPABASE_URL,APP_CONFIG.SUPABASE_PUBLISHABLE_KEY);renderMeals();updateStatus();window.addEventListener('online',updateStatus);window.addEventListener('offline',updateStatus);const logo=document.querySelector('.hero img');let hold;logo.addEventListener('pointerdown',()=>hold=setTimeout(openAdminPin,5000));['pointerup','pointerleave','pointercancel'].forEach(e=>logo.addEventListener(e,()=>clearTimeout(hold)));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');}
function updateStatus(){['staffStatus','studentStatus'].forEach(id=>{const e=$(id);if(!e)return;e.textContent=navigator.onLine?'● Online':'● Offline';e.className='status '+(navigator.onLine?'online':'offline')});}
function showMode(mode){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(mode).classList.add('active');if(mode==='staff'){refreshDashboard();refreshTimer=setInterval(refreshDashboard,10000);$('staffReg').focus()}else{clearInterval(refreshTimer);refreshTimer=null;if(mode==='student')$('studentReg').focus();}}
function renderMeals(){renderMealSet('staffMeals','staff');renderMealSet('studentMeals','student')}
function renderMealSet(id,type){const box=$(id);box.innerHTML='';MEALS.forEach(m=>{const b=document.createElement('button');b.className='meal'+((type==='staff'?staffMeal:studentMeal)===m?' sel':'');b.textContent=m;b.onclick=()=>{if(type==='staff')staffMeal=m;else studentMeal=m;renderMeals()};box.appendChild(b)})}
function openStaffPin(){pinPurpose='staff';$('pinTitle').textContent='Enter Staff PIN';$('pinHelp').textContent='Enter the four-digit PIN to continue.';openPin()}
function openAdminPin(){pinPurpose='admin';$('pinTitle').textContent='Enter Admin PIN';$('pinHelp').textContent='Enter the PIN to open administration.';openPin()}
function openPin(){$('pinInput').value='';$('pinError').textContent='';$('pinModal').classList.add('open');setTimeout(()=>$('pinInput').focus(),80)}
function closePin(){$('pinModal').classList.remove('open')}
function submitPin(){if($('pinInput').value!==PIN){$('pinError').textContent='Incorrect PIN';return}closePin();if(pinPurpose==='staff')showMode('staff');else $('adminModal').classList.add('open')}
function closeAdmin(){$('adminModal').classList.remove('open')}
async function refreshDashboard(){if(!navigator.onLine)return;const r=await db.rpc('staff_dashboard',{p_pin:PIN,p_service_date:today()});if(r.error)return;const d=r.data||{};const counts=d.counts||{};$('counts').innerHTML=MEALS.map(m=>`<div class="count"><div class="n">${counts[m]||0}</div><div class="l">${esc(m)}</div></div>`).join('');$('plan').innerHTML=`<span style="font-size:11px;text-transform:uppercase">To cook today</span><br>Lunch <b>${d.lunch_to_cook||0}</b> &nbsp;·&nbsp; Supper <b>${d.supper_to_cook||0}</b>`}
function norm(v){return String(v||'').replace(/\D/g,'').slice(0,5)}
async function checkIn(type){if(!navigator.onLine){showResult('bad','✕','No connection','<p>Please connect to the internet and try again.</p>');return}const meal=type==='staff'?staffMeal:studentMeal,input=$(type+'Reg'),reg=norm(input.value);if(!meal){showResult('bad','✕','Choose a meal','<p>Select the meal first.</p>');return}if(!/^\d{5}$/.test(reg)){showResult('bad','✕','Check the number','<p>Enter a five-digit registration number.</p>');return}const btn=$(type+'CheckBtn');btn.disabled=true;btn.textContent='Saving...';const fn=type==='staff'?'staff_check_in':'check_in_student_public';const args=type==='staff'?{p_pin:PIN,p_registration_number:reg,p_meal_session:meal,p_service_date:today()}:{p_registration_number:reg,p_meal_session:meal,p_service_date:today()};const r=await db.rpc(fn,args);btn.disabled=false;btn.textContent='Check in';if(r.error){showResult('bad','✕','Could not save',`<p>${esc(r.error.message)}</p>`);return}handleResult(r.data||{},reg,meal);input.value='';if(type==='staff')refreshDashboard()}
function handleResult(d,reg,meal){const name=d.full_name?`<div class="name">${esc(d.full_name)}</div>`:'';const number=`<p>${esc(d.registration_number||reg)}</p>`;if(d.status==='checked_in')showResult('ok','✓','CHECKED IN',`${name}${number}<p>${esc(d.meal_session||meal)}</p><p>Enjoy your meal.</p>`);else if(d.status==='duplicate')showResult('dup','⚠','ALREADY CHECKED IN',`${name}${number}<p>${esc(d.meal_session||meal)}</p>`);else if(d.status==='not_eligible')showResult('bad','✕','NOT ELIGIBLE',`${name}${number}<p>${esc(d.message||'Required earlier meal not found.')}</p>`);else if(d.status==='not_found')showResult('bad','✕','NOT ON THE LIST',`${number}<p>${esc(d.message||'Registration number not found.')}</p>`);else showResult('bad','✕','CHECK-IN NOT SAVED',`<p>${esc(d.message||'Please try again.')}</p>`)}
function showResult(cls,ico,title,body){$('resultBox').className='resultbox '+cls;$('resultBox').innerHTML=`<div class="ico">${ico}</div><h2>${esc(title)}</h2>${body}`;$('result').classList.add('open');clearTimeout(timer);timer=setTimeout(hideResult,3000)}
function hideResult(){$('result').classList.remove('open');const active=document.querySelector('.screen.active');if(active?.id==='staff')$('staffReg').focus();if(active?.id==='student')$('studentReg').focus()}
async function exportCsv(scope){const r=await db.rpc('staff_export',{p_pin:PIN,p_scope:scope,p_service_date:today()});if(r.error){showResult('bad','✕','Export failed',`<p>${esc(r.error.message)}</p>`);return}const rows=r.data||[];const headers=['service_date','meal_session','registration_number','full_name','checked_in_at','check_in_source'];const csv=[headers.join(','),...rows.map(x=>headers.map(h=>'"'+String(x[h]??'').replace(/"/g,'""')+'"').join(','))].join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download=`meal-checkins-${scope}-${today()}.csv`;a.click();URL.revokeObjectURL(a.href)}
async function clearToday(){if(!confirm('Clear all check-ins for today? This cannot be undone.'))return;const r=await db.rpc('admin_clear_day',{p_pin:PIN,p_service_date:today()});if(r.error){showResult('bad','✕','Could not clear',`<p>${esc(r.error.message)}</p>`);return}closeAdmin();showResult('ok','✓','CLEARED','<p>Today’s records have been removed.</p>');refreshDashboard()}
async function startScan(target){scanTarget=target;if(!navigator.mediaDevices?.getUserMedia){showResult('bad','✕','Camera unavailable','<p>This browser cannot access the camera.</p>');return}try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});$('video').srcObject=stream;await $('video').play();$('cam').classList.add('open');scanning=true;scanLoop()}catch(e){showResult('bad','✕','Camera blocked','<p>Allow camera access in your browser settings.</p>')}}
function stopScan(){scanning=false;if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;$('cam').classList.remove('open')}
async function scanLoop(){if(!scanning)return;const v=$('video');if(v.readyState>=2){try{if('BarcodeDetector'in window){const det=new BarcodeDetector({formats:['qr_code']});const codes=await det.detect(v);if(codes[0]?.rawValue)return acceptScan(codes[0].rawValue)}else if(window.jsQR){const c=document.createElement('canvas'),x=c.getContext('2d');c.width=v.videoWidth;c.height=v.videoHeight;x.drawImage(v,0,0);const code=jsQR(x.getImageData(0,0,c.width,c.height).data,c.width,c.height);if(code?.data)return acceptScan(code.data)}}catch(e){}}requestAnimationFrame(scanLoop)}
function acceptScan(value){const reg=norm(value);if(/^\d{5}$/.test(reg)){stopScan();$(scanTarget+'Reg').value=reg;checkIn(scanTarget)}}
init();
